version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: <%= underscore(serviceName) %>_ob_service_ai_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - transport.host=0.0.0.0
    ports:
      - '9200:9200'
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

